# 1. Import the numpy package under the name np and Print the numpy version and the configuration

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

# 2. Create a null vector of size 10

In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 3. Create Simple 1-D array and check type and check data types in array 

In [5]:
arr = np.array([1, 2, 3, 23, 56, 100])
  
print(type(arr))
  
print('Datatype:', arr.dtype)

<class 'numpy.ndarray'>
Datatype: int32


# 4. How to find number of dimensions, bytes per element and bytes of memory used? 

In [10]:
df = np.array([1, 2, 3, 23, 56, 100])
print (df.ndim)
print (df.nbytes)
print (df.size)

1
24
6


# 5. Create a null vector of size 10 but the fifth value which is 1

In [20]:
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 6.Create a vector with values ranging from 10 to 49


In [21]:
s = np.arange(10,50)
s

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 7. Reverse a vector (first element becomes last)

In [24]:
x = np.arange(50)
s1 = x[::-1]
s1

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 8. Create a 3x3 matrix with values ranging from 0 to 8

In [25]:
m = np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [29]:
n =np.nonzero([1,2,0,0,4,0])
print(n)

(array([0, 1, 4], dtype=int64),)


# 10.Create a 3x3 identity matrix

In [31]:
r =np.eye(3)
print(r)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 11.Create a 3x3x3 array with random values

In [30]:
i=np.random.random((3,3,3))
print(i)

[[[0.23976276 0.03897506 0.64466598]
  [0.30505628 0.02041399 0.96955575]
  [0.67879709 0.94791173 0.79264992]]

 [[0.14958995 0.84998794 0.65681568]
  [0.46992053 0.48097442 0.80258175]
  [0.76968848 0.05619773 0.7980431 ]]

 [[0.36377499 0.51944489 0.5642652 ]
  [0.98809886 0.45363252 0.25086245]
  [0.50559456 0.54257421 0.7060089 ]]]


# 12. Create a 10x10 array with random values and find the minimum and maximum values

In [32]:
a=np.random.random((10,10))
amin,amax=a.min(),a.max()
print(amin,amax)

0.002929662153091872 0.9976116670628552


# 13. Create a random vector of size 30 and find the mean value


In [33]:
y=np.random.random(30)
m=y.mean()
print(m)

0.36963268900178675


 # 14.Create a 2d array with 1 on the border and 0 inside

In [36]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 15. How to add a border (filled with 0's) around an existing array? 


In [37]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# 17. How to Convert a 1D array to a 2D array with 2 rows



In [53]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print ('Before reshaping:',arr, '\n') 

arr1 = arr.reshape(4, 2)
print ('After reshaping having dimension 4x2:',arr1, '\n')

arr2 = arr.reshape(2, 4)
print ('After reshaping having dimension 2x4:', arr2, '\n')


Before reshaping: [1 2 3 4 5 6 7 8] 

After reshaping having dimension 4x2: [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

After reshaping having dimension 2x4: [[1 2 3 4]
 [5 6 7 8]] 



# 19.Write a program to show how Numpy taking less memory compared to Python List?

In [48]:
import sys 
S= range(1000)
print("Size of each element of list in bytes: ",sys.getsizeof(S))
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S)) 
D= np.arange(1000)
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  4
Size of the whole Numpy array in bytes:  4000


# 20. Write a program to show how Numpy taking less time compared to Python List?

In [49]:
# importing required packages
import numpy
import time


# size of arrays and lists
size = 1000000

# declaring lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# declaring arrays
array1 = numpy.arange(size)
array2 = numpy.arange(size)

# Concatenation
print("\nConcatenation:")

# list
initialTime = time.time()
list1 = list1 + list2

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array = numpy.concatenate((array1, array2),
						axis = 0)

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


# Dot Product
dot = 0
print("\nDot Product:")

# list
initialTime = time.time()
for a, b in zip(list1, list2):
		dot = dot + (a * b)
		
# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array = numpy.dot(array1, array2)

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


# Scalar Addtion
print("\nScalar Addition:")

# list
initialTime = time.time()
list1 =[i + 2 for i in range(size)]

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array1 = array1 + 2

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


# Deletion
print("\nDeletion: ")

# list
initialTime = time.time()
del(list1)

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
del(array1)

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")



Concatenation:
Time taken by Lists : 0.017008304595947266 seconds
Time taken by NumPy Arrays : 0.0010035037994384766 seconds

Dot Product:
Time taken by Lists : 0.6055572032928467 seconds
Time taken by NumPy Arrays : 0.003341197967529297 seconds

Scalar Addition:
Time taken by Lists : 0.6189675331115723 seconds
Time taken by NumPy Arrays : 0.0408322811126709 seconds

Deletion: 
Time taken by Lists : 0.028879642486572266 seconds
Time taken by NumPy Arrays : 0.00407719612121582 seconds
